// Layout and SVG chart classes.
export const hostTrendClasses = {
  "trendValue": "netdive-trend-trendValue",
  "trendValueNumber": "netdive-trend-trendValueNumber",
  "trendValueUnit": "netdive-trend-trendValueUnit",
  "networkCurrentBar": "netdive-trend-networkCurrentBar",
  "networkCurrentItem": "netdive-trend-networkCurrentItem",
  "networkSeriesLabel": "netdive-trend-networkSeriesLabel",
  "rxText": "netdive-trend-rxText",
  "networkCurrentDivider": "netdive-trend-networkCurrentDivider",
  "txText": "netdive-trend-txText",
  "tooltipContent": "netdive-trend-tooltipContent",
  "tooltipSectionDivider": "netdive-trend-tooltipSectionDivider",
  "tooltipSection": "netdive-trend-tooltipSection",
  "tooltipSectionTitle": "netdive-trend-tooltipSectionTitle",
  "tooltipRow": "netdive-trend-tooltipRow",
  "svg": "netdive-trend-svg",
  "guide": "netdive-trend-guide",
  "axis": "netdive-trend-axis",
  "axisLabel": "netdive-trend-axisLabel",
  "timeLabel": "netdive-trend-timeLabel",
  "fill": "netdive-trend-fill",
  "line": "netdive-trend-line",
  "lineSecondary": "netdive-trend-lineSecondary",
  "antEmpty": "netdive-trend-antEmpty",
  "headerActions": "netdive-trend-headerActions",
  "rangeSelect": "netdive-trend-rangeSelect",
  "loading": "netdive-trend-loading",
  "refreshing": "netdive-trend-refreshing",
  "grid": "netdive-trend-grid"
}
