import * as assert from 'assert'
import * as fs from 'fs'
import * as path from 'path'

import { kubernetesDetailPreviewFixtures } from '../src/DataPanels/common/KubernetesDetailPreviewFixtures'

const root = path.resolve(__dirname, '..')
const read = (file: string) => fs.readFileSync(path.join(root, file), 'utf8')

describe('Kubernetes detail UI contract', () => {
    it('keeps structured modal copy actions visible and supports embedded-browser fallback', () => {
        const common = read('src/DataPanels/common/DetailComponents.tsx')
        const table = read('src/DataPanels/common/KubernetesStructuredDataTable.tsx')
        const commonCss = read('src/DataPanels/common/DetailComponents.css')
        assert.ok(common.includes("document.execCommand('copy')"))
        assert.ok(common.includes('result.catch(() => copyTextWithLegacySelection(value))'))
        assert.ok(common.includes('placement="topRight"'))
        assert.ok(common.includes('getPopupContainer={() => document.body}'))
        assert.ok(table.includes("width: columnWidths?.action || (hasExpandableRows ? 72 : 44)"))
        assert.ok(commonCss.includes('.netdive-k8s-structured-table__actions'))
        assert.ok(commonCss.includes('.netdive-detail-copy-tooltip .ant-tooltip-inner'))
    })

    it('covers normal, exceptional, empty, failure, long-name, and narrow states', () => {
        const states = new Set(kubernetesDetailPreviewFixtures.map(fixture => fixture.key))
        ;['normal', 'warning', 'danger', 'empty', 'fetch-error', 'long-name', 'narrow-panel']
            .forEach(state => assert.ok(states.has(state as any), `missing ${state} fixture`))
        assert.ok(kubernetesDetailPreviewFixtures.some(fixture => fixture.panelWidth <= 340))
        assert.ok(kubernetesDetailPreviewFixtures.some(fixture => fixture.resourceName.length > 50))
    })

    it('keeps the cluster and node panels on canonical shared components', () => {
        const cluster = read('src/DataPanels/KubernetesClusterDetailPanel.tsx')
        const node = read('src/DataPanels/KubernetesNodeDetailPanel.tsx')
        ;['DetailSectionCard', 'BasicInfoRows', 'StatusSummaryGrid', 'ResourceMetricBlock', 'RelatedResourceGrid', 'CompactEmptyState']
            .forEach(component => {
                assert.ok(cluster.includes(component), `cluster does not use ${component}`)
                assert.ok(node.includes(component), `node does not use ${component}`)
            })
        assert.ok(cluster.includes('StatusEvidenceRow'))
        assert.ok(node.includes('StatusEvidenceRow'))
    })

    it('anchors every Kubernetes information tooltip to the shared icon-only trigger', () => {
        const common = read('src/DataPanels/common/DetailComponents.tsx')
        const commonCss = read('src/DataPanels/common/DetailComponents.css')
        const confidence = read('src/DataPanels/common/KubernetesAnalysisConfidence.tsx')
        const podUsage = read('src/DataPanels/common/KubernetesPodUsageTable.tsx')
        const panels = [
            'src/DataPanels/KubernetesClusterDetailPanel.tsx',
            'src/DataPanels/KubernetesNodeDetailPanel.tsx',
            'src/DataPanels/KubernetesNamespaceDetailPanel.tsx',
            'src/DataPanels/KubernetesWorkloadDetailPanel.tsx',
            'src/DataPanels/KubernetesPodDetailPanel.tsx',
            'src/DataPanels/KubernetesServiceDetailPanel.tsx',
            'src/DataPanels/KubernetesStorageDetailPanel.tsx'
        ].map(read)

        assert.ok(common.includes('export const DetailInfoTooltip'))
        assert.ok(common.includes('placement="top"'))
        assert.ok(common.includes('arrowPointAtCenter'))
        assert.ok(common.includes("trigger={['hover', 'focus']}"))
        assert.ok(common.includes('getPopupContainer={detailTooltipPopupContainer}'))
        assert.ok(common.includes('autoAdjustOverflow'))
        assert.ok(common.includes("joinClassNames('netdive-detail-info-tooltip-trigger', className)"))
        assert.ok(common.includes('tabIndex={0}'))
        assert.ok(common.includes('onClick={event => event.stopPropagation()}'))
        assert.ok(!common.includes('operationalTooltipTrigger'))
        assert.ok(commonCss.includes('.netdive-detail-info-tooltip-trigger > .anticon > svg'))
        assert.ok(commonCss.includes('#netdive-detail-tooltip-portal'))
        assert.ok(commonCss.includes('position: fixed'))
        assert.ok(commonCss.includes('overflow: hidden'))
        assert.ok(confidence.includes('<DetailInfoTooltip'))
        assert.ok(podUsage.includes('<DetailInfoTooltip'))
        panels.forEach(panel => assert.ok(!panel.includes('<InfoCircleOutlined'), 'panel bypasses the shared information-tooltip trigger'))
    })

    it('defines the fixed visual tokens and removes node-specific duplicate metric rows', () => {
        const tokens = read('src/DataPanels/common/DetailDesignTokens.css')
        const common = read('src/DataPanels/common/DetailComponents.css')
        const commonComponents = read('src/DataPanels/common/DetailComponents.tsx')
        const cluster = read('src/DataPanels/KubernetesClusterDetailPanel.tsx')
        const clusterCss = read('src/DataPanels/KubernetesClusterDetailPanel.css')
        const node = read('src/DataPanels/KubernetesNodeDetailPanel.tsx')
        const nodeCss = read('src/DataPanels/KubernetesNodeDetailPanel.css')
        ;[
            '--netdive-detail-panel-gap',
            '--netdive-detail-card-padding-x',
            '--netdive-detail-row-height',
            '--netdive-detail-evidence-row-padding-y',
            '--netdive-detail-evidence-column-gap',
            '--netdive-detail-evidence-info-gap',
            '--netdive-detail-progress-height',
            '--netdive-detail-result-state-width',
            '--netdive-detail-result-value-width',
            '--netdive-detail-resource-icon-size',
            '--netdive-detail-resource-value-min-width',
            '--netdive-detail-resource-action-width',
            '--netdive-detail-resource-column-gap',
            '--netdive-detail-font-panel-title: 15px',
            '--netdive-detail-font-section-title: 14px',
            '--netdive-detail-font-primary-value: 16px',
            '--netdive-detail-font-body-label: 12px',
            '--netdive-detail-font-supporting-text: 11px',
            '--netdive-detail-font-status-tag: 11px',
            '--netdive-detail-font-tooltip-body: 12px'
        ].forEach(token => assert.ok(tokens.includes(token), `missing ${token}`))
        assert.ok(!nodeCss.includes('netdive-k8s-node-detail__resource-row'))
        assert.ok(!nodeCss.includes('netdive-k8s-node-detail__dependency-metrics'))
        assert.ok(!nodeCss.includes('netdive-k8s-node-detail__metric-rows'))
        assert.ok(cluster.includes('BasicInfoRows density="compact"'))
        assert.ok(node.includes('BasicInfoRows density="compact"'))
        assert.ok(!clusterCss.includes('basic-kv .netdive-detail-kv__row'))
        assert.ok(!nodeCss.includes('basic-kv .netdive-detail-kv__row'))
        assert.ok(common.includes('@container (max-width: 360px)'))
        assert.ok(common.includes('.netdive-detail-empty--compact:not(.ant-empty)'))
        assert.ok(commonComponents.includes("joinClassNames('netdive-list-modal', className)"))
    })

    it('keeps node information hierarchy and workload exploration compact', () => {
        const node = read('src/DataPanels/KubernetesNodeDetailPanel.tsx')
        const nodeCss = read('src/DataPanels/KubernetesNodeDetailPanel.css')
        const common = read('src/DataPanels/common/DetailComponents.tsx')
        assert.ok(node.includes('DetailAdvancedInfo'))
        assert.ok(common.includes('netdive-detail-advanced-collapse'))
        assert.ok(node.includes('density="compact"'))
        assert.ok(common.includes("density?: 'default' | 'compact'"))
        assert.ok(!nodeCss.includes('netdive-k8s-node-detail__condition-summary'))
        assert.ok(node.includes('riskModalConfigs'))
        assert.ok(node.includes("riskModal: 'single-replica'"))
        assert.ok(node.includes("riskModal: 'local-storage'"))
        assert.ok(node.includes('workloadModalOpen'))
        assert.ok(node.includes('HistoryModal'))
        assert.ok(node.includes('title={`전체 워크로드 컨트롤러 ${workloads.length}개`}'))
        assert.ok(node.includes("label: 'Pod 사용량'"))
        assert.ok(node.includes('nodeConditionDescription(condition)'))
        assert.ok(node.includes('tooltipRawValue={rawCondition}'))
        assert.ok(node.includes('tooltipRawValue={NODE_METRIC_MAPPING.singleReplicaRaw}'))
        assert.ok(node.includes('현재 노드에 배치된 Deployment·StatefulSet 중 replica가 1개인 워크로드입니다.'))
        assert.ok(node.includes("onClick: workloads.length ? () => this.setState({ workloadModalOpen: true"))
        assert.ok(!node.includes('workloadsExpanded'))
        assert.ok(!nodeCss.includes('workload-filters'))
        assert.ok(!nodeCss.includes('workload-more'))
        assert.ok(!nodeCss.includes('workload-heading'))
        assert.ok(!nodeCss.includes('workload-list'))
        assert.ok(!nodeCss.includes('condition-tooltip'))
        assert.ok(node.includes('return `${display} Core`'))
    })

    it('keeps risk evaluation rows separate from connected-resource exploration', () => {
        const node = read('src/DataPanels/KubernetesNodeDetailPanel.tsx')
        const nodeCss = read('src/DataPanels/KubernetesNodeDetailPanel.css')
        assert.ok(!node.includes('title="관련 위험 워크로드"'))
        assert.ok(!node.includes('relatedRiskWorkloads'))
        assert.ok(!node.includes('DetailCompactResourceList'))
        assert.ok(!node.includes('DetailCompactResourceItem'))
        assert.ok(node.includes("'single-replica': { title: '단일 Replica 워크로드'"))
        assert.ok(node.includes("'local-storage': { title: '로컬 스토리지 의존 워크로드'"))
        assert.ok(node.includes('const localStorageDependencies = kubernetesNodeLocalStorageDependencies(connected.pods, allNodes)'))
        assert.ok(node.includes("pending: { title: 'Pending Pod'"))
        assert.ok(node.includes("restart: { title: '최근 재시작 Pod'"))
        assert.ok(node.includes("'oom-killed': { title: '현재·최근 OOMKilled Pod'"))
        assert.ok(node.includes("onClick={() => this.setState({ riskModal: 'single-replica' })}"))
        assert.ok(node.includes("onClick={() => this.setState({ riskModal: 'local-storage' })}"))
        assert.ok(node.includes("this.setState({ riskModal: item[5] as RiskModalKey })"))
        assert.ok(node.includes('집계 결과는 있으나 연결된 리소스를 현재 토폴로지에서 확인할 수 없습니다.'))
        assert.ok(!node.includes('netdive-k8s-node-detail__problem-list-title'))
        assert.ok(!nodeCss.includes('netdive-k8s-node-detail__problem-list-title'))
        assert.ok(node.includes("label: 'Pod', count: connected.pods.length"))
        assert.ok(node.includes("this.setState({ podModalOpen: true })"))
        assert.ok(node.includes('title={`전체 Pod ${connected.pods.length}개`}'))
        assert.ok(node.includes('title={`전체 워크로드 컨트롤러 ${workloads.length}개`}'))
        assert.ok(node.includes("title: '이 노드의 Pod'"))
        assert.ok(node.includes("['현재·최근 OOMKilled 파드'"))
        assert.ok(node.includes('현재 종료 상태이거나 조회 기간 내 OOMKilled가 발생한 Pod입니다.'))
        assert.strictEqual((node.match(/childrenColumnName="__netdiveNoTreeChildren"/g) || []).length, 2)
        assert.ok(node.includes("metadata={item[6]}"))
        assert.ok(node.includes("{ key: 'window', label: '조회 기간', value: '최근 1시간' }"))
        assert.ok(node.includes("{ key: 'history', label: '누적 이력', value: `${restartHistoryPodCount}개` }"))
        assert.ok(node.includes("{ key: 'history', label: '누적 이력', value: `${oomKilledHistoryPodCount}개` }"))
        assert.ok(!node.includes('evidenceTooltip='))
        const common = read('src/DataPanels/common/DetailComponents.tsx')
        const commonCss = read('src/DataPanels/common/DetailComponents.css')
        assert.ok(common.includes('metadata?: ReadonlyArray'))
        assert.ok(common.includes('netdive-detail-evidence-row__metadata'))
        const evidenceRule = commonCss.match(/\.netdive-detail-evidence-row__evidence\s*\{([\s\S]*?)\}/)
        assert.ok(evidenceRule)
        assert.ok(!evidenceRule![1].includes('line-clamp'))
        assert.ok(!evidenceRule![1].includes('ellipsis'))
        assert.ok(!evidenceRule![1].includes('overflow: hidden'))
    })

    it('uses the shared operational hierarchy for cluster warning and error states', () => {
        const cluster = read('src/DataPanels/KubernetesClusterDetailPanel.tsx')
        const clusterCss = read('src/DataPanels/KubernetesClusterDetailPanel.css')
        const common = read('src/DataPanels/common/DetailComponents.tsx')
        const commonCss = read('src/DataPanels/common/DetailComponents.css')
        assert.ok(cluster.includes('summaryTitle="상태 요약"'))
        assert.ok(cluster.includes('metricsTitle="자원 현황"'))
        assert.ok(cluster.includes('<DetailCardSubsectionHeader title="현재 이상"'))
        assert.ok(cluster.includes('title="과거 이력"'))
        assert.ok(cluster.includes('title="누적/종료 이력"'))
        assert.ok(cluster.includes("columnHeaders={{ state: '상태', value: '대상 수', action: true }}"))
        assert.ok(cluster.includes('actionIndicator={!!item.onClick}'))
        assert.ok(!cluster.includes('renderPodStatusSummary'))
        assert.ok(!clusterCss.includes('netdive-k8s-cluster-detail__pod-status-summary'))
        assert.ok(!clusterCss.includes('netdive-k8s-cluster-detail__abnormal-status'))
        assert.ok(common.includes('summaryTitle?: React.ReactNode'))
        assert.ok(common.includes('metricsTitle?: React.ReactNode'))
        assert.ok(common.includes('actionIndicator?: boolean'))
        assert.ok(commonCss.includes('.netdive-detail-evidence-row.has-action'))
    })

    it('uses one empty self marker and exclusive direct-child state badges on topology cards', () => {
        const topology = read('src/Topology.tsx')
        const topologyCss = read('src/Topology.css')
        const badgeAggregation = read('src/KubernetesTopologyBadgeAggregation.ts')
        const badgeView = read('src/TopologyStatusBadge.tsx')
        const app = read('src/App.tsx')
        const groupDetail = read('src/DataPanels/GroupDetailPanel.tsx')
        const groupDetailCss = read('src/DataPanels/GroupDetailPanel.css')

        assert.ok(!topology.includes('KubernetesTopologyDescendantWarning'))
        assert.ok(!topology.includes('node-descendant-warning'))
        assert.ok(!topology.includes('warningReserve'))
        assert.ok(!topology.includes('node-kubernetes-status-dot'))
        assert.ok(topology.includes('if (isKubernetesResource(d.data.wrapped)) return 18'))
        assert.ok(!topology.includes('displayedStatusBadgeCount'))
        assert.ok(!topology.includes('topologyStatusBadgeSingleReserveWidth'))
        assert.ok(topology.includes('<TopologyStatusBadgeRail'))
        assert.ok(topology.includes('summary={badgeGroupSummary(d, badges)}'))
        assert.ok(!topology.includes('g.node-exco-badge-slot'))
        assert.ok(!topology.includes('compactStatusBadges'))
        assert.ok(topology.includes('x={cardWidthForNode(d) / 2 - 12}'))
        assert.ok(topology.includes('y={-cardHeightForNode(d) / 2}'))
        assert.ok(!topology.includes('y={-cardHeightForNode(d) / 2 + 12}'))
        assert.ok(topologyCss.includes('.node-exco-badge.is-problem .node-exco-circle'))
        assert.ok(topologyCss.includes('.node-exco-badge.is-running .node-exco-circle'))
        assert.ok(!topologyCss.includes('.node-kubernetes-status-dot'))
        assert.ok(!topologyCss.includes('.topology-descendant-warning-trigger'))
        assert.ok(badgeAggregation.includes("key: 'self-problem'"))
        assert.ok(badgeAggregation.includes("key: 'direct-self-problem'"))
        assert.ok(badgeAggregation.includes("key: 'direct-descendant-problem'"))
        assert.ok(badgeAggregation.includes("key: 'direct-healthy'"))
        assert.ok(badgeAggregation.includes("displayText: '!'"))
        assert.ok(badgeAggregation.includes('Uses exactly the next visible topology layer'))
        assert.ok(badgeAggregation.includes('Group nodes are real direct'))
        assert.ok(!badgeAggregation.includes('allowedDirectChildTypes'))
        assert.ok(badgeView.includes("trigger={['hover', 'focus']}"))
        assert.ok(badgeView.includes('arrowPointAtCenter'))
        assert.ok(badgeView.includes('placement="top"'))
        assert.ok(badgeView.includes('netdive-topology-badge-tooltip__title'))
        assert.ok(badgeView.includes('netdive-topology-badge-tooltip__description'))
        assert.ok(badgeView.includes('netdive-topology-badge-tooltip__details'))
        assert.ok(badgeView.includes("item.label ? '' : 'is-description'"))
        assert.ok(badgeView.includes('netdive-topology-badge-tooltip__bullet'))
        assert.ok(topologyCss.includes('.netdive-topology-badge-tooltip__row'))
        assert.ok(topologyCss.includes('.netdive-topology-badge-tooltip__row.is-description'))
        assert.ok(topologyCss.includes('grid-template-columns: 8px minmax(0, 1fr)'))
        assert.ok(badgeAggregation.includes("title: '자체 이상'"))
        assert.ok(badgeAggregation.includes("title: '하위 자원 이상'"))
        assert.ok(badgeAggregation.includes("title: '정상'"))
        assert.ok(badgeAggregation.includes("'direct-self-problem': '자체 이상'"))
        assert.ok(badgeAggregation.includes("'direct-descendant-problem': '하위 자원 이상'"))
        assert.ok(badgeAggregation.includes("'direct-healthy': '정상'"))
        assert.ok(!badgeAggregation.includes("'direct-self-problem': '이상 감지'"))
        assert.ok(badgeAggregation.includes('const groupNode = isTopologyGroup(node)'))
        assert.ok(badgeAggregation.includes('export const kubernetesResourceSelfStatus'))
        assert.ok(badgeAggregation.includes("state: 'unknown'"))
        assert.ok(badgeAggregation.includes("collection: 'stale'"))
        assert.ok(badgeAggregation.includes("collection: 'unavailable'"))
        assert.ok(badgeAggregation.includes('groupNode && direct.selfProblematic.length > 0'))
        assert.ok(badgeAggregation.includes('...direct.selfProblematic, ...direct.descendantProblematic'))
        assert.ok(badgeAggregation.includes("label: `${resourceTypeProblemLabel(item.type)} 이상`"))
        assert.ok(badgeAggregation.includes("label: `${resourceTypeProblemLabel(item.type)} 정상`"))
        assert.ok(badgeAggregation.includes("const scopePrefix = isTopologyGroup(node) ? '' : '하위 '"))
        assert.ok(badgeAggregation.includes('title: `${scopePrefix}${childLabel} 상태`'))
        assert.ok(badgeAggregation.includes('totalLabel: `${scopePrefix}${childLabel} 총 ${total}개`'))
        assert.ok(!badgeAggregation.includes('하위 이상 직접 자식'))
        assert.ok(!badgeAggregation.includes('직접 하위 전체'))
        assert.ok(!badgeAggregation.includes('정상 직접 하위'))
        assert.ok(badgeView.includes('className={`node-exco-badge is-${tone}`}'))
        assert.ok(badgeView.includes('<circle className="node-exco-circle"'))
        assert.ok(badgeView.includes('export const TopologyStatusBadgeRail'))
        assert.ok(badgeView.includes('className="netdive-topology-numeric-badge-group"'))
        assert.ok(badgeView.includes('netdive-topology-numeric-badge-group__trigger'))
        assert.ok(badgeView.includes('title={badgeGroupSummaryContent(summary)}'))
        assert.ok(badgeView.includes("item.badge.key === 'self-problem' || item.badge.key === 'self-inactive'"))
        assert.ok(badgeView.includes("item.badge.key !== 'self-problem' && item.badge.key !== 'self-inactive'"))
        assert.ok(badgeView.includes('text={text} pointerEvents="all"'))
        assert.ok(badgeView.includes('netdive-topology-badge-summary__state'))
        assert.ok(badgeView.includes('text=""'))
        assert.ok(badgeView.includes('export const TopologyStatusBadgeGroup'))
        assert.ok(badgeView.includes('export const TopologyStatusBadgeLegend'))
        assert.ok(app.includes("import { TopologyStatusBadgeLegend } from './TopologyStatusBadge'"))
        assert.ok(app.includes('<TopologyStatusBadgeLegend />'))
        assert.ok(badgeView.includes('상태 배지 의미'))
        assert.ok(badgeView.includes('현재 리소스 이상'))
        assert.ok(badgeView.includes('하위 자원 이상'))
        assert.ok(badgeView.includes('선택한 리소스 자체에 이상이 있는 상태'))
        assert.ok(badgeView.includes('자체와 아래 계층 모두 이상이 없는 자원 수'))
        assert.ok(badgeView.includes('숫자는 현재 단계의 자원 상태 개수를 나타냅니다.'))
        assert.ok(badgeView.includes('trigger="click"'))
        assert.ok(badgeView.includes('<Tooltip title="토폴로지 범례" placement="bottom"'))
        assert.ok(badgeView.includes('<Tabs.TabPane tab="상태 배지" key="status">'))
        assert.ok(badgeView.includes('<Tabs.TabPane tab="노드 표현" key="node">'))
        assert.ok(badgeView.includes('className="netdive-topology-status-legend__tabs"'))
        assert.ok(!badgeView.includes('className="netdive-detail-navigation-tabs netdive-topology-status-legend__tabs"'))
        assert.ok(badgeView.includes('실제 인프라 또는 Kubernetes 리소스를 나타냅니다.'))
        assert.ok(badgeView.includes('같은 종류의 자원을 묶은 화면 구성용 그룹'))
        assert.ok(badgeView.includes('파란 테두리로 표시되며'))
        assert.ok(badgeView.includes('자원 유형 또는 소속 정보를 나타냅니다.'))
        assert.ok(badgeView.includes('visible={open ? false : undefined}'))
        assert.ok(topologyCss.includes('.netdive-topology-status-legend-trigger'))
        assert.ok(topologyCss.includes('.netdive-topology-status-legend__item'))
        assert.ok(topologyCss.includes('width: 348px'))
        assert.ok(topologyCss.includes('.netdive-topology-node-legend__item'))
        assert.ok(topologyCss.includes('.netdive-topology-status-legend__tabs .ant-tabs-content-holder'))
        assert.ok(topologyCss.includes('display: block'))
        assert.ok(topologyCss.includes('font-size: 18px'))
        assert.ok(badgeView.includes('export const TOPOLOGY_STATUS_BADGE_RADIUS = 15'))
        assert.ok(badgeView.includes('export const TOPOLOGY_STATUS_BADGE_STEP = 34'))
        assert.ok(badgeView.includes('const TOPOLOGY_STATUS_BADGE_LIST_GAP = 4'))
        assert.ok(badgeView.includes('TOPOLOGY_STATUS_BADGE_LIST_VIEWPORT_SCALE'))
        assert.ok(badgeView.includes('const TOPOLOGY_STATUS_BADGE_VIEWBOX_PADDING = 2'))
        assert.ok(badgeView.includes('shapeRendering="geometricPrecision"'))
        assert.ok(badgeView.includes('x={TOPOLOGY_STATUS_BADGE_VIEWBOX_PADDING + radius + Math.max(0, badges.length - 1) * step}'))
        assert.ok(groupDetail.includes('kubernetesTopologyCountBadges(node)'))
        assert.ok(groupDetail.includes('kubernetesTopologyBadgeGroupSummary(node, topologyBadges)'))
        assert.ok(groupDetail.includes('<TopologyStatusBadgeGroup'))
        assert.ok(groupDetail.includes('summary={topologyBadgeSummary}'))
        assert.ok(!groupDetail.includes('variant="compact"'))
        assert.ok(groupDetail.includes('className="netdive-group-detail-topologyBadges"'))
        assert.ok(groupDetailCss.includes('.netdive-group-detail-topologyBadges'))
        assert.ok(!badgeView.includes('<title'))
        assert.ok(read('src/DataPanels/KubernetesNodeDetailPanel.tsx').includes('kubernetesResourceSelfStatus(this.props.node, {'))
        assert.ok(read('src/DataPanels/KubernetesNodeDetailPanel.tsx').includes("collectionState: this.state.loading ? 'uncollected' : this.state.error ? 'failed' : 'collected'"))
        assert.ok(read('src/DataPanels/KubernetesNamespaceDetailPanel.tsx').includes('kubernetesResourceSelfStatus(this.props.node, {'))
        assert.ok(read('src/DataPanels/KubernetesNamespaceDetailPanel.tsx').includes("collectionState: this.state.loading ? 'uncollected' : this.state.error ? 'failed' : 'collected'"))
        assert.ok(read('src/DataPanels/KubernetesWorkloadDetailPanel.tsx').includes('kubernetesResourceSelfStatus(this.props.node, extra)'))
        assert.ok(read('src/DataPanels/KubernetesPodDetailPanel.tsx').includes('getPodClassification(this.props.node)'))
    })

    it('filters Kubernetes topology by canonical attention paths with a one-time auto expand toggle', () => {
        const app = read('src/App.tsx')
        const topology = read('src/Topology.tsx')
        const aggregation = read('src/KubernetesTopologyBadgeAggregation.ts')
        assert.ok(aggregation.includes('export const kubernetesTopologyAttentionPathIDs'))
        assert.ok(aggregation.includes('kubernetesTopologyNodeNeedsAttention(node)'))
        assert.ok(aggregation.includes("['problem', 'unknown'].includes"))
        assert.ok(topology.includes('setKubernetesProblemsOnly(enabled: boolean)'))
        assert.ok(topology.includes('if (this.kubernetesProblemsOnly === enabled) return'))
        assert.ok(topology.includes('this.kubernetesAttentionPathIDs.has(node.id)'))
        assert.ok(topology.includes('renderedKubernetesBadgeChildren'))
        assert.ok(topology.includes('kubernetesTopologyCountBadges(wrapper.wrapped, renderedKubernetesBadgeChildren(wrapper))'))
        assert.ok(topology.includes('child.type === WrapperType.Group'))
        assert.ok(topology.includes('renderedGroupIDs.has(owningGroup.wrapped.id)'))
        assert.ok(topology.includes('this.kubernetesProblemsExpandedSnapshot'))
        assert.ok(topology.includes('this.kubernetesProblemsGroupSnapshot'))
        assert.ok(app.includes('<FilterOutlined />'))
        assert.ok(app.includes('"이상 자원만 보기"'))
        assert.ok(app.includes('"전체 자원 보기"'))
        assert.ok(app.includes('classes.topologyIconButtonActive'))
        // Search continues to pin matches inside the already filtered tree;
        // it must not disable or replace the attention-path predicate.
        const searchStart = app.indexOf('onSearchChange(selected:')
        const searchBlock = app.slice(searchStart, searchStart + 2500)
        assert.ok(!searchBlock.includes('setKubernetesProblemsOnly(false)'))
    })

    it('keeps stopped Mold clusters visible but suppresses their Kubernetes descendants', () => {
        const app = read('src/App.tsx')
        const aggregation = read('src/KubernetesTopologyBadgeAggregation.ts')
        const badgeView = read('src/TopologyStatusBadge.tsx')
        const topologyCss = read('src/Topology.css')
        assert.ok(app.includes('clusterNode.data.MoldClusterState = configured.state'))
        assert.ok(app.includes('kubernetesTopologyHasInactiveClusterAncestor(node)'))
        assert.ok(app.includes('type !== "cluster"'))
        assert.ok(aggregation.includes("state: 'inactive'"))
        assert.ok(aggregation.includes("key: 'self-inactive'"))
        assert.ok(aggregation.includes("key: 'direct-inactive'"))
        assert.ok(aggregation.includes("tone: 'inactive'"))
        assert.ok(aggregation.includes("displayText: '!'"))
        assert.ok(aggregation.includes("title: '비활성'"))
        assert.ok(aggregation.includes('현재 Mold에서 정지 상태인 클러스터입니다.'))
        assert.ok(read('src/DataPanels/GroupDetailPanel.tsx').includes('kubernetesTopologyCountBadges(node)'))
        assert.ok(badgeView.includes("label: '비활성'"))
        assert.ok(badgeView.includes('정지 등으로 현재 운영되지 않는 자원'))
        assert.ok(topologyCss.includes('.node-exco-badge.is-inactive .node-exco-circle'))
    })

    it('uses the shared operational tooltip hierarchy for cluster and node KPIs', () => {
        const common = read('src/DataPanels/common/DetailComponents.tsx')
        const commonCss = read('src/DataPanels/common/DetailComponents.css')
        const node = read('src/DataPanels/KubernetesNodeDetailPanel.tsx')
        const nodeCss = read('src/DataPanels/KubernetesNodeDetailPanel.css')
        const clusterCss = read('src/DataPanels/KubernetesClusterDetailPanel.css')
        assert.ok(common.includes('tooltipDetail?: React.ReactNode'))
        assert.ok(common.includes('tooltipRawValue?: React.ReactNode'))
        assert.ok(common.includes('원본 값: {rawValue}'))
        assert.ok(common.includes('overlayClassName="netdive-operational-tooltip"'))
        assert.ok(commonCss.includes('.netdive-operational-tooltip .ant-tooltip-inner'))
        assert.ok(commonCss.includes('max-width: 320px'))
        assert.ok(commonCss.includes('white-space: normal'))
        assert.ok(node.includes('현재 노드에 할당된 고유 Pod 중 Succeeded·Failed 종료 Pod와 삭제 대상을 제외한 수입니다.'))
        assert.ok(node.includes('현재 노드에 할당된 고유 Pod 중 현재 이상 상태로 판정된 Pod 수입니다.'))
        assert.ok(node.includes('이 노드에 새 Pod를 배치할 수 있는 상태입니다.'))
        assert.ok(node.includes('노드에 설정된 Taint 수이며 Pod 스케줄링 제약에 영향을 줄 수 있습니다.'))
        assert.ok(!nodeCss.includes('operational-tooltip'))
        assert.ok(!clusterCss.includes('operational-tooltip'))
    })

    it('keeps node accuracy rules on shared presentation contracts', () => {
        const node = read('src/DataPanels/KubernetesNodeDetailPanel.tsx')
        const common = read('src/DataPanels/common/DetailComponents.tsx')
        const commonCss = read('src/DataPanels/common/DetailComponents.css')
        const selection = read('src/SelectionPanel.tsx')
        assert.ok(selection.includes('titleMaxLines={isKubernetesLongNameResource ? 2 : 1}'))
        assert.ok(selection.includes('const displayTitle = isKubernetesLongNameResource ? fullTitle'))
        assert.ok(common.includes('titleMaxLines?: 1 | 2'))
        assert.ok(commonCss.includes('-webkit-line-clamp: 2'))
        assert.ok(node.includes("{ label: 'Kubelet 버전'"))
        assert.ok(node.includes('formatKubernetesValueState'))
        assert.ok(node.includes('basis="Allocatable"'))
        assert.ok(common.includes('basis?: React.ReactNode'))
        assert.ok(node.includes('const currentPodCount = connected.pods.length'))
        assert.ok(node.includes('{this.renderCapacity(currentPodCount)}'))
        assert.ok(node.includes("label: 'Pod', count: connected.pods.length"))
        assert.ok(node.includes('const problemCount = connected.problemPods.length'))
        assert.ok(node.includes('const recentRestartPodCount = connected.recentRestartPods.length'))
        assert.ok(node.includes('value: `${restartHistoryPodCount}개`'))
        assert.ok(node.includes('최근 1시간 동안 발생한 중요 이벤트가 없습니다.'))
        assert.ok(node.includes('<KubernetesRecentEvents'))
        assert.ok(!node.includes('netdive-k8s-node-detail__events'))
    })

    it('keeps risk evidence rows on one shared three-column status pattern', () => {
        const common = read('src/DataPanels/common/DetailComponents.tsx')
        const commonCss = read('src/DataPanels/common/DetailComponents.css')
        const node = read('src/DataPanels/KubernetesNodeDetailPanel.tsx')
        const cluster = read('src/DataPanels/KubernetesClusterDetailPanel.tsx')
        const nodeCss = read('src/DataPanels/KubernetesNodeDetailPanel.css')
        const clusterCss = read('src/DataPanels/KubernetesClusterDetailPanel.css')
        assert.ok(common.includes('DetailStatusIndicator'))
        assert.ok(common.includes('StatusEvidenceList'))
        assert.ok(common.includes('netdive-detail-evidence-row__state'))
        assert.ok(common.includes('netdive-detail-evidence-row__value'))
        assert.ok(commonCss.includes('var(--netdive-detail-result-state-width)'))
        assert.ok(commonCss.includes('var(--netdive-detail-result-value-width)'))
        assert.ok(commonCss.includes('.netdive-detail-evidence-list'))
        assert.ok(commonCss.includes('.netdive-detail-status-indicator.is-success'))
        assert.ok(common.includes('<i />'))
        assert.ok(!common.includes("? <DetailBadge tone={tone} className={className}>{children}</DetailBadge>"))
        assert.ok(commonCss.includes('.netdive-detail-status-indicator.is-warning'))
        assert.ok(commonCss.includes('.netdive-detail-status-indicator.is-danger'))
        assert.ok(commonCss.includes('.netdive-detail-status-indicator.is-default'))
        assert.ok(commonCss.includes('.netdive-detail-evidence-row__value.is-grade'))
        assert.ok(commonCss.includes('.netdive-detail-evidence-row__value.is-score'))
        assert.ok(cluster.includes("<StatusEvidenceList columnHeaders={{ state: '상태', value: '평가' }}>"))
        assert.ok(node.includes("<StatusEvidenceList columnHeaders={{ state: '상태', value: '대상 수' }}>"))
        assert.ok(!node.includes("value: '현재 수'"))
        assert.ok(common.includes('columnHeaders?:'))
        assert.ok(common.includes('netdive-detail-evidence-list__column-headers'))
        assert.ok(commonCss.includes('.netdive-detail-evidence-list__column-headers'))
        assert.ok(commonCss.includes('.netdive-detail-evidence-list__column-headers > span:nth-child(n + 3)'))
        assert.ok(cluster.includes('status={{ label, tone }}'))
        assert.ok(cluster.includes('valueVariant={valueVariant}'))
        assert.ok(!clusterCss.includes('netdive-k8s-cluster-detail__resilience-rows'))
        assert.ok(!nodeCss.includes('netdive-k8s-node-detail__risk-rows'))
        assert.ok(!commonCss.includes('.netdive-detail-evidence-row__interactive .netdive-detail-evidence-row'))
        assert.ok(!commonCss.includes('.netdive-detail-evidence-row__result'))
        assert.ok(node.includes("status={singleReplicaWorkloadCount > 0 ? { label: '보완 권장', tone: 'warning' }"))
        assert.ok(node.includes("{ label: tone === 'danger' ? '위험' : '보완 권장', tone: tone === 'danger' ? 'danger' : 'warning' }"))
        assert.ok(!node.includes('<DetailBadge tone="warning">확인 필요</DetailBadge>'))
        assert.ok(!node.includes('<DetailBadge tone={tone}>확인 필요</DetailBadge>'))
    })

    it('keeps shared connected-resource labels readable for up to two lines', () => {
        const commonCss = read('src/DataPanels/common/DetailComponents.css')
        assert.ok(commonCss.includes('minmax(var(--netdive-detail-resource-value-min-width), max-content)'))
        assert.ok(commonCss.includes('var(--netdive-detail-resource-action-width)'))
        assert.ok(commonCss.includes('max-height: calc(var(--netdive-detail-line-body-label) + var(--netdive-detail-line-body-label))'))
        assert.ok(commonCss.includes('-webkit-line-clamp: 2'))
        assert.ok(commonCss.includes('overflow-wrap: anywhere'))
        assert.ok(commonCss.includes('grid-auto-rows: var(--netdive-detail-resource-height)'))
        assert.ok(!commonCss.includes('max-height: 28px'))
    })

    it('keeps the namespace panel on the cluster and node shared detail grammar', () => {
        const namespace = read('src/DataPanels/KubernetesNamespaceDetailPanel.tsx')
        const namespaceCss = read('src/DataPanels/KubernetesNamespaceDetailPanel.css')
        const recentEvents = read('src/DataPanels/common/KubernetesRecentEvents.tsx')
        const visualPreview = read('tests/visual/KubernetesDetailVisualRegression.tsx')
        const resourceConfigurationCard = read('src/DataPanels/common/KubernetesResourceConfigurationCard.tsx')
        const containerDetails = read('src/DataPanels/common/KubernetesContainerDetails.tsx')
        const workload = read('src/DataPanels/KubernetesWorkloadDetailPanel.tsx')
        const pod = read('src/DataPanels/KubernetesPodDetailPanel.tsx')
        const podCss = read('src/DataPanels/KubernetesPodDetailPanel.css')
        ;[
            '<DetailSectionCard',
            '<BasicInfoRows',
            '<DetailAdvancedInfo',
            '<KubernetesMetadataRows',
            '<StatusSummaryGrid',
            '<DetailNavigationTabs',
            '<DetailMetaInfoRow',
            '<StatusEvidenceList',
            '<StatusEvidenceRow',
            '<ResourceMetricBlock',
            '<DetailMetricRow',
            '<RelatedResourceGrid',
            '<KubernetesRecentEvents',
            '<HistoryModal'
        ].forEach(component => assert.ok(namespace.includes(component), `namespace is missing ${component}`))
        assert.ok(namespace.includes("problem: { title: translate('kubernetesProblemPods')"))
        assert.ok(namespace.includes("podModal: item[4] as NamespacePodModalKey"))
        assert.ok(namespace.includes("<StatusEvidenceList columnHeaders={{ state: '상태', value: '결과' }}>"))
        assert.ok(namespace.includes("<StatusEvidenceList columnHeaders={{ state: '상태', value: '대상 수' }}>"))
        assert.ok(namespace.includes('KUBERNETES_DETAIL_LABELS.oomKilledPods'))
        assert.ok(namespace.includes("{ key: 'window', label: '조회 기간', value: '최근 1시간' }"))
        assert.ok(namespace.includes("key: 'collection'"))
        assert.ok(namespace.includes("label: '데이터 수집 상태'"))
        assert.ok(namespace.includes('value: collection.label'))
        assert.ok(!namespace.includes('<DetailCollectionStatusRow'))
        assert.ok(namespace.includes('kubernetesCollectionPresentation(['))
        assert.ok(namespace.includes("label: 'Requests/Limits', state: requestsLimitsCollectionState"))
        assert.ok(namespace.includes("label: '사용량 메트릭', state: usageMetricsCollected ? 'collected' : 'uncollected'"))
        assert.ok(namespace.includes("label: 'Kubernetes 객체'"))
        assert.ok(namespace.includes('label: KUBERNETES_DETAIL_LABELS.workloadsAndPods'))
        assert.ok(namespace.includes('label: KUBERNETES_DETAIL_LABELS.services'))
        assert.ok(namespace.includes("label: '이벤트'"))
        assert.ok(resourceConfigurationCard.includes('kubernetesConfigurationCoveragePresentation('))
        assert.ok(namespace.includes('KUBERNETES_DETAIL_LABELS.namespaceStatus'))
        assert.ok(namespace.includes('KUBERNETES_DETAIL_LABELS.runningPods'))
        assert.ok(namespace.includes('registerKubernetesPodCurrentStatusSnapshots(detail?.pods)'))
        assert.ok(resourceConfigurationCard.includes('KUBERNETES_DETAIL_LABELS.cpuRequests'))
        assert.ok(resourceConfigurationCard.includes('KUBERNETES_DETAIL_LABELS.memoryLimits'))
        assert.ok(namespace.includes("modalTitle: '네임스페이스 어노테이션'"))
        assert.ok(!namespace.includes("label: 'Annotation'"))
        assert.ok(namespace.includes('<DetailNavigationTabs'))
        assert.ok(!namespace.includes('<Tabs'))
        assert.ok(!namespace.includes('<Dropdown'))
        const commonComponents = read('src/DataPanels/common/DetailComponents.tsx')
        const commonCss = read('src/DataPanels/common/DetailComponents.css')
        const antThemeCss = read('src/antd-netdive.css')
        const kubernetesPresentation = read('src/DataPanels/common/KubernetesDataPresentation.ts')
        assert.ok(commonComponents.includes("activeKey={overflowActive ? '__overflow_active__' : activeKey}"))
        assert.ok(commonComponents.includes('moreIcon={<EllipsisOutlined />}'))
        assert.ok(commonComponents.includes('tabBarExtraContent={overflowTrigger}'))
        assert.ok(commonComponents.includes('<Dropdown'))
        assert.ok(commonComponents.includes('<Menu'))
        assert.ok(commonComponents.includes('<Button'))
        assert.ok(commonComponents.includes('icon={<EllipsisOutlined />}'))
        assert.ok(!commonComponents.includes('<button\n                type="button"\n                aria-label="추가 탭"'))
        assert.ok(commonComponents.includes('getPopupContainer={() => document.body}'))
        assert.ok(!commonComponents.includes('netdive-detail-navigation-tabs__menu-label'))
        assert.ok(commonComponents.includes('overlayClassName="netdive-mold-dropdown"'))
        assert.ok(!commonComponents.includes('overlayClassName="netdive-detail-navigation-tabs__overflow-menu"'))
        assert.ok(!commonCss.includes('.netdive-detail-navigation-tabs__overflow-menu'))
        assert.ok(antThemeCss.includes('.netdive-mold-dropdown .ant-dropdown-menu'))
        assert.ok(antThemeCss.includes('.netdive-mold-dropdown .ant-dropdown-menu-item-selected'))
        assert.ok(antThemeCss.includes('box-shadow: 0 2px 8px rgba(0, 0, 0, 0.15)'))
        assert.ok(antThemeCss.includes('background-color: #e6f7ff'))
        assert.ok(antThemeCss.includes('z-index: 2147483656'))
        assert.ok(namespace.includes('overflowTabs={['))
        assert.ok(namespace.includes("{ key: 'services', label: KUBERNETES_DETAIL_LABELS.services, count: connectedServices.length }"))
        assert.ok(namespace.includes("{ key: 'ingress', label: 'Ingress', count:"))
        assert.ok(namespace.includes("{ key: 'configuration', label: '정책 및 설정', count:"))
        assert.ok(namespace.includes("{ key: 'storage', label: '스토리지', count:"))
        assert.ok(commonCss.includes('.netdive-detail-navigation-tabs .ant-tabs-content-holder'))
        assert.ok(commonCss.includes('.netdive-detail-meta-info-row'))
        assert.ok(commonCss.includes('.netdive-detail-meta-info-row > span > :first-child'))
        assert.ok(commonCss.includes('justify-self: end'))
        assert.ok(commonCss.includes('.netdive-detail-meta-info-row .netdive-detail-status-indicator'))
        const metadataModal = read('src/DataPanels/common/KubernetesMetadataModal.tsx')
        assert.ok(metadataModal.includes('export const KubernetesMetadataRows'))
        assert.ok(metadataModal.includes('className="netdive-detail-metadata-row is-interactive"'))
        assert.ok(metadataModal.includes('className="netdive-detail-metadata-row is-empty"'))
        assert.ok(metadataModal.includes('<strong>{item.label}</strong><span>없음</span>'))
        assert.ok(!metadataModal.includes('const visibleItems = normalized.filter(item => item.entries.length > 0)'))
        assert.ok(!namespace.includes('<DetailMetadataSummary'))
        assert.ok(!workload.includes('<DetailMetadataSummary'))
        assert.ok(!namespace.includes('excludedKeys: [\'kubernetes.io/metadata.name\']'))
        const structuredTable = read('src/DataPanels/common/KubernetesStructuredDataTable.tsx')
        const selectorModal = read('src/DataPanels/common/KubernetesSelectorSummary.tsx')
        assert.ok(metadataModal.includes('<KubernetesStructuredDataTable'))
        assert.ok(metadataModal.includes('<KubernetesRawJsonCollapse'))
        assert.ok(metadataModal.indexOf('<KubernetesModalResourceContext') < metadataModal.indexOf('<KubernetesModalSection'))
        assert.ok(metadataModal.indexOf('<KubernetesModalSection') < metadataModal.indexOf('<KubernetesRawJsonCollapse'))
        assert.ok(selectorModal.indexOf('<KubernetesModalResourceContext') < selectorModal.indexOf('title={`라벨 선택자'))
        assert.ok(selectorModal.indexOf('title={`라벨 선택자') < selectorModal.indexOf('title={`조건 선택자'))
        assert.ok(selectorModal.indexOf('title={`조건 선택자') < selectorModal.indexOf('<KubernetesRawJsonCollapse'))
        assert.ok(structuredTable.includes('<Divider />'))
        assert.ok(structuredTable.includes('KubernetesModalResourceContext'))
        assert.ok(structuredTable.includes('KubernetesModalSection'))
        assert.ok(structuredTable.includes('<Table<KubernetesStructuredDataRow>'))
        assert.ok(structuredTable.includes('className="netdive-modal-table netdive-k8s-structured-table"'))
        assert.ok(structuredTable.includes('size="small"'))
        assert.ok(structuredTable.includes('rowKey="id"'))
        assert.ok(structuredTable.includes('expandedRowKeys: expandedKeys'))
        assert.ok(structuredTable.includes('setExpandedKeys(current => toggleKubernetesStructuredExpandedKey(current, row.id))'))
        assert.ok(structuredTable.includes('event.stopPropagation()'))
        assert.ok(structuredTable.includes('destroyInactivePanel'))
        assert.ok(structuredTable.includes('className="netdive-k8s-structured-table__empty"'))
        assert.ok(!metadataModal.includes('ellipsis={{'))
        assert.ok(!structuredTable.includes('ellipsis={{'))
        assert.ok(!structuredTable.includes('Popover'))
        assert.ok(!structuredTable.includes('onMouseEnter'))
        assert.ok(commonCss.includes('background: #fafafa'))
        assert.ok(commonCss.includes('border-bottom-color: #f0f0f0'))
        assert.ok(commonCss.includes('.netdive-k8s-modal-section > .ant-divider'))
        assert.ok(commonCss.includes('.netdive-k8s-structured-table__empty.netdive-detail-empty--compact'))
        assert.ok(commonCss.includes('border: 1px solid var(--netdive-detail-section-divider)'))
        assert.ok(commonCss.includes('margin: 8px 0 6px'))
        assert.ok(commonCss.includes('padding: 14px 16px'))
        assert.ok(!metadataModal.includes('tooltip="키 복사"'))
        assert.ok(!metadataModal.includes('netdive-k8s-metadata-modal__list'))
        assert.ok(!metadataModal.includes('netdive-k8s-metadata-modal__entry'))
        assert.ok(!commonComponents.includes("? '키 없음'"))
        assert.ok(metadataModal.includes('<RightOutlined />'))
        assert.ok(!commonComponents.includes('상세 보기'))
        assert.ok(!commonComponents.includes('DetailMetadataList'))
        assert.ok(!commonComponents.includes('export const DetailResourceConfigurationList'))
        assert.ok(commonCss.includes('.netdive-detail-metadata-modal pre'))
        assert.ok(commonCss.includes('.netdive-detail-metadata-row.is-interactive:hover'))
        assert.ok(!commonCss.includes('.netdive-detail-metadata-list'))
        assert.ok(!commonCss.includes('.netdive-detail-resource-configuration__headers'))
        assert.ok(namespace.includes('<KubernetesResourceConfigurationCard coverage={resourceCoverage} />'))
        assert.ok(resourceConfigurationCard.includes("description = '활성 파드 컨테이너의 요청량·제한량 설정 현황입니다.'"))
        assert.strictEqual((namespace.match(/활성 Pod의 일반 컨테이너와 initContainer 중 해당 리소스 값/g) || []).length, 0)
        assert.ok(resourceConfigurationCard.includes("value: '설정 컨테이너'"))
        assert.ok(resourceConfigurationCard.includes("mode?: 'aggregate' | 'single'"))
        assert.ok(resourceConfigurationCard.includes("if (mode === 'single') return <BasicInfoRows"))
        assert.ok(resourceConfigurationCard.includes("secondaryValue: '설정 합계'"))
        assert.ok(resourceConfigurationCard.includes('kubernetesConfiguredResourceTotalPresentation({'))
        assert.ok(resourceConfigurationCard.includes('secondaryValue={row.total}'))
        assert.ok(resourceConfigurationCard.includes('valuesUnavailable={!row.collected}'))
        assert.ok(resourceConfigurationCard.includes('kubernetesConfigurationCoveragePresentation('))
        assert.ok(resourceConfigurationCard.includes('kubernetesResourceConfigurationCollectionState('))
        assert.ok(commonComponents.includes('secondaryValue?: React.ReactNode'))
        assert.ok(commonComponents.includes('valuesUnavailable?: boolean'))
        assert.ok(commonComponents.includes("const renderedValue = valuesUnavailable ? '확인 불가' : value"))
        assert.ok(commonCss.includes('.netdive-detail-evidence-row.has-unavailable-values'))
        assert.ok(commonCss.includes('.netdive-detail-evidence-row.has-secondary-value'))
        assert.ok(namespace.includes("onClick={quotaConfigured ? () => this.setState({ policyModal: 'quota' }) : undefined}"))
        assert.ok(namespace.includes("onClick={limitRangeConfigured ? () => this.setState({ policyModal: 'limitRange' }) : undefined}"))
        assert.ok(namespace.includes('KUBERNETES_DETAIL_LABELS.resourceQuota'))
        assert.ok(namespace.includes('KUBERNETES_DETAIL_LABELS.limitRange'))
        assert.ok(commonComponents.includes("resourceQuota: '리소스 할당량'"))
        assert.ok(commonComponents.includes("limitRange: '기본 리소스 제한'"))
        assert.ok(!commonComponents.includes("resourceQuota: '리소스 할당량(ResourceQuota)'"))
        assert.ok(!commonComponents.includes("limitRange: '기본 리소스 제한(LimitRange)'"))
        assert.ok(kubernetesPresentation.includes("key === 'kubectl.kubernetes.io/last-applied-configuration'"))
        assert.ok(kubernetesPresentation.includes("'kubectl.kubernetes.io/last-applied-configuration': 'kubectl 적용 구성'"))
        assert.ok(metadataModal.includes('전체 ${kindLabel} 복사'))
        assert.ok(namespace.includes('ResourceQuota'))
        assert.ok(namespace.includes('LimitRange'))
        assert.ok(namespace.includes("label: 'PVC'"))
        assert.ok(!namespace.includes("label: 'PV'"))
        assert.ok(!namespace.includes("label: 'StorageClass'"))
        assert.ok(namespace.includes('childrenColumnName="__netdiveNoTreeChildren"'))
        assert.ok(!namespaceCss.includes('overflow-x: auto'))
        assert.ok(!namespaceCss.includes('navigation'))
        assert.ok(!namespaceCss.includes('netdive-k8s-namespace-detail__resource-policy'))
        assert.ok(namespace.includes('집계 결과는 있으나 연결된 파드를 현재 토폴로지에서 확인할 수 없습니다.'))
        assert.ok(namespace.includes("tooltip: '파드 생성 이후 Evicted, restartCount 1 이상, 과거 OOMKilled"))
        assert.ok(namespace.includes('파드 UID 기준으로 중복 제거합니다.'))
        assert.ok(resourceConfigurationCard.includes("row.tooltip.replace('활성 파드', '이 컨테이너')"))
        assert.ok(workload.includes('<KubernetesContainerDetails'))
        assert.ok(pod.includes('<KubernetesContainerDetails'))
        assert.ok(pod.includes('kubernetesContainerStateReason(container)'))
        assert.ok(!pod.includes('container.waitingReason || container.terminatedReason || container.lastTerminatedReason'))
        assert.ok(pod.includes('현재 파드 상태로 인해 확인된 서비스 가용성 영향이 없습니다.'))
        assert.ok(commonComponents.includes("kubernetesImpactLabel(impact)"))
        assert.ok(containerDetails.includes('mode="single"'))
        assert.ok(containerDetails.includes('kubernetesSingleContainerResourceCoverage('))
        assert.ok(!pod.includes('<dl>'))
        assert.ok(!podCss.includes('netdive-k8s-pod-detail__resources'))
        assert.ok(!resourceConfigurationCard.includes('evidence={row.tooltip}'))
        assert.ok(commonComponents.includes('item.tooltip && item.onClick ? <Tooltip'))
        assert.ok(commonComponents.includes('interactive || labelTooltip !== undefined'))
        assert.ok(!namespace.includes("import './KubernetesNodeDetailPanel.css'"))
        assert.ok(!namespace.includes('netdive-k8s-node-detail'))
        assert.ok(!namespace.includes('<DetailBadge'))
        assert.ok(!namespace.includes('<DetailKeyValueList'))
        assert.ok(!namespace.includes('<ConnectedResourcesSection'))
        assert.ok(!namespace.includes('<DetailResourceGrid'))
        assert.ok(!namespace.includes('<KubernetesStateSeparation'))
        assert.ok(!namespace.includes('state={<DetailStatusIndicator'))
        assert.ok(!namespace.includes('detail.cpuRequests'))
        assert.ok(!namespace.includes('detail.cpuLimits'))
        assert.ok(!namespace.includes('detail.memoryRequests'))
        assert.ok(!namespace.includes('detail.memoryLimits'))
        assert.ok(namespace.includes("value={!quotaCollected ? '확인 불가' : quotaCount}"))
        assert.ok(namespace.includes("value={!limitRangeCollected ? '확인 불가' : limitRangeCount}"))
        assert.ok(namespace.includes('valuesUnavailable={!quotaCollected}'))
        assert.ok(namespace.includes('valuesUnavailable={!limitRangeCollected}'))
        const cluster = read('src/DataPanels/KubernetesClusterDetailPanel.tsx')
        const clusterCss = read('src/DataPanels/KubernetesClusterDetailPanel.css')
        assert.ok(cluster.includes('<DetailNavigationTabs'))
        assert.ok(!cluster.includes('<Tabs'))
        assert.ok(!clusterCss.includes('netdive-k8s-cluster-detail__navigation'))
        assert.ok(commonCss.includes('width: 96px'))
        assert.ok(commonCss.includes('.netdive-detail-navigation-tabs__label small'))
        assert.ok(!namespaceCss.includes('!important'))
        assert.ok(!namespaceCss.includes('font-size: 10'))
        assert.ok(recentEvents.includes('<DetailStatusIndicator tone={group.tone}>'))
        assert.ok(!recentEvents.includes('<DetailBadge'))
        assert.ok(visualPreview.includes("type PreviewResource = 'cluster' | 'node' | 'namespace'"))
        assert.ok(visualPreview.includes('<DetailStatusIndicator'))
        assert.ok(!visualPreview.includes('<DetailBadge'))
    })

    it('keeps every Kubernetes resource panel on the shared detail grammar', () => {
        const panels = [
            {
                name: 'workload',
                source: read('src/DataPanels/KubernetesWorkloadDetailPanel.tsx'),
                required: ['<DetailSectionCard', '<BasicInfoRows', '<DetailAdvancedInfo', '<KubernetesMetadataRows', '<StatusSummaryGrid', '<KubernetesConditionRows', '<KubernetesContainerDetails', '<KubernetesRecentEvents']
            },
            {
                name: 'pod',
                source: read('src/DataPanels/KubernetesPodDetailPanel.tsx'),
                required: ['<DetailSectionCard', '<BasicInfoRows', '<DetailAdvancedInfo', '<KubernetesMetadataRows', '<StatusSummaryGrid', '<KubernetesConditionRows', '<KubernetesContainerDetails', '<KubernetesRecentEvents']
            },
            {
                name: 'service',
                source: read('src/DataPanels/KubernetesServiceDetailPanel.tsx'),
                required: ['<DetailSectionCard', '<BasicInfoRows', '<DetailAdvancedInfo', '<KubernetesMetadataRows', '<StatusSummaryGrid', '<StatusEvidenceRow', '<RelatedResourceGrid', '<KubernetesRecentEvents']
            },
            {
                name: 'storage',
                source: read('src/DataPanels/KubernetesStorageDetailPanel.tsx'),
                required: ['<DetailSectionCard', '<BasicInfoRows', '<DetailAdvancedInfo', '<KubernetesMetadataRows', '<StatusSummaryGrid', '<RelatedResourceGrid', '<KubernetesRecentEvents']
            },
            {
                name: 'relationship',
                source: read('src/DataPanels/KubernetesRelationshipResourceDetailPanel.tsx'),
                required: ['<DetailSectionCard', '<BasicInfoRows', '<DetailAdvancedInfo', '<KubernetesMetadataRows', '<ConnectedResourceListSection']
            }
        ]
        panels.forEach(panel => {
            panel.required.forEach(component => assert.ok(panel.source.includes(component), `${panel.name} is missing ${component}`))
            assert.ok(!panel.source.includes("import './KubernetesNodeDetailPanel.css'"), `${panel.name} imports node panel CSS`)
            assert.ok(!panel.source.includes('className="netdive-k8s-node-detail'), `${panel.name} uses the node panel wrapper`)
            assert.ok(!panel.source.includes('<DetailKeyValueList'), `${panel.name} uses the legacy key/value alias`)
            assert.ok(!panel.source.includes('<DetailSection '), `${panel.name} uses the legacy section alias`)
            assert.ok(!panel.source.includes('<ConnectedResourcesSection'), `${panel.name} uses the legacy related-resource alias`)
        })
    })

    it('keeps StorageClass policy, relations and event evidence on shared contracts', () => {
        const storage = read('src/DataPanels/KubernetesStorageDetailPanel.tsx')
        const structuredAction = read('src/DataPanels/common/KubernetesStructuredDataModalAction.tsx')
        const connectedModal = read('src/DataPanels/common/KubernetesConnectedResourceModal.tsx')
        assert.ok(storage.includes("title={type === 'storageclass' ? '스토리지 클래스 기본 정보'"))
        assert.ok(storage.includes('kubernetesDefaultStorageClass(annotations'))
        assert.ok(storage.includes('kubernetesBooleanSettingLabel(allowVolumeExpansion'))
        assert.ok(storage.includes('kubernetesReclaimPolicyLabel(reclaimPolicy)'))
        assert.ok(storage.includes('kubernetesVolumeBindingModePresentation(volumeBindingMode)'))
        assert.ok(storage.includes('tooltipRawValue: volumeBindingModePresentation.rawValue'))
        assert.ok(storage.includes(" : '설정되지 않음'"))
        assert.ok(storage.includes('<KubernetesStructuredDataModalAction'))
        assert.ok(storage.includes('action={type === \'storageclass\' && defaultStorageClass === true'))
        assert.ok(storage.includes('기본 스토리지 클래스'))
        assert.ok(!storage.includes("label: '기본 스토리지 클래스'"))
        assert.ok(storage.includes("? [{ key: 'usage', items: directItems }]"))
        assert.ok(storage.includes("this.storageClassName(item) === name"))
        assert.ok(storage.includes("count: storageClassPVCs.length"))
        assert.ok(storage.includes("count: storageClassPVs.length"))
        assert.ok(storage.includes("type !== 'persistentvolumeclaim' && type !== 'persistentvolume') || eventsCollected"))
        assert.ok(storage.includes("lookbackLabel={type === 'storageclass' ? '최근 24시간'"))
        assert.ok(storage.includes("type === 'persistentvolumeclaim' || type === 'persistentvolume' ? '최근 1시간'"))
        assert.ok(storage.includes('<DetailMetaInfoRow items={['))
        assert.ok(storage.includes("key: 'current-problem'"))
        assert.ok(storage.includes("key: 'collection'"))
        assert.ok(storage.includes("label: 'PVC 기본 정보', collected: pvcBasicCollected, essential: true"))
        assert.ok(storage.includes("label: '요청/할당 용량', state: pvcCapacityState, essential: true"))
        assert.ok(storage.includes("label: '과거 스토리지 이벤트 이력', state: pvcEventCollectionState"))
        assert.ok(storage.includes("rawStatusLabel=\"바인딩 상태\""))
        assert.ok(storage.includes('kubernetesPvPhaseLabel(phase)'))
        assert.ok(storage.includes('kubernetesPvSourcePresentation(spec)'))
        assert.ok(storage.includes("label: 'PV 기본 정보', collected: !!name, essential: true"))
        assert.ok(storage.includes('tooltipDetail: pvCollection.detail'))
        assert.ok(storage.includes('<DetailLongValue value={pvClaimName} copy />'))
        assert.ok(!storage.includes("label: '고정 노드'"))
        assert.ok(storage.includes("label: '노드 배치 조건'"))
        assert.ok(storage.includes('kubernetesPvNodeAffinityPresentation(pvNodeAffinity)'))
        assert.ok(storage.includes('onClick: () => this.focus(nodes)'))
        assert.ok(storage.includes('rawTitle="원본 nodeAffinity JSON 보기"'))
        assert.ok(!storage.includes("{ key: 'current', label: '현재 문제'"))
        assert.ok(storage.includes("value: <DetailLongValue value={String(meta.UID || this.props.node.id)} copy />"))
        assert.ok(storage.includes('visible: eventsCollected'))
        assert.ok(storage.includes("label: '상위 워크로드'"))
        assert.ok(storage.includes("type === 'persistentvolumeclaim'\n                ? [{ key: 'usage', items: pvcRelatedItems }]"))
        assert.ok(storage.includes('resolveKubernetesPodTopController(pod, nodes)'))
        assert.ok(!storage.includes('수집된 프로비저닝 실패 이력이 없습니다.'))
        assert.ok(structuredAction.includes('<HistoryModal'))
        assert.ok(structuredAction.includes('<KubernetesStructuredDataTable'))
        assert.ok(connectedModal.includes('<ConnectedResourceListSection'))
        const selectionPanel = read('src/SelectionPanel.tsx')
        assert.ok(selectionPanel.includes("'persistentvolumeclaim', 'persistentvolume', 'storageclass'"))
        assert.ok(selectionPanel.includes('titleMaxLines={isKubernetesLongNameResource ? 2 : 1}'))
        const common = read('src/DataPanels/common/DetailComponents.tsx')
        assert.ok(common.includes('const visibleMetrics = metrics.filter(metric => metric.visible !== false)'))
        assert.ok(common.includes('<DetailInfoTooltip'))
        assert.ok(common.includes('placement="top"'))
        assert.ok(common.includes("joinClassNames('netdive-detail-info-tooltip-trigger', className)"))
        assert.ok(!common.includes('netdive-detail-meta-info-row__value-trigger'))
        const commonCss = read('src/DataPanels/common/DetailComponents.css')
        assert.ok(commonCss.includes('.netdive-detail-meta-info-row > span > .netdive-detail-meta-info-row__value'))
        assert.ok(commonCss.includes('justify-self: end'))
    })

    it('keeps the Pod panel compact and routes repeated structures through common components', () => {
        const pod = read('src/DataPanels/KubernetesPodDetailPanel.tsx')
        const podCss = read('src/DataPanels/KubernetesPodDetailPanel.css')
        const containers = read('src/DataPanels/common/KubernetesContainerDetails.tsx')
        const conditions = read('src/DataPanels/common/KubernetesConditionRows.tsx')
        const volumes = read('src/DataPanels/common/KubernetesVolumeList.tsx')
        const structured = read('src/DataPanels/common/KubernetesStructuredDataTable.tsx')
        const commonCss = read('src/DataPanels/common/DetailComponents.css')
        assert.ok(pod.includes('label: \'준비 컨테이너\''))
        assert.ok(pod.includes('label: \'누적 재시작 이력\''))
        assert.ok(pod.includes('recentRestart ? \'최근 재시작 감지\''))
        assert.ok(!pod.includes("key: 'services', label:"))
        assert.ok(pod.includes('<KubernetesContainerDetails'))
        assert.ok(pod.includes('showRawValue={false}'))
        assert.ok(pod.includes('<KubernetesVolumeList'))
        assert.ok(pod.includes('kubernetesPodVolumePresentations(\n            this.podSpec(),\n            containers,'))
        assert.ok(pod.includes('!this.state.loading && !this.state.error'))
        assert.ok(pod.includes("title: '상위 워크로드'"))
        assert.ok(pod.includes("title: '배치 노드'"))
        assert.ok(pod.includes('lookbackLabel="최근 1시간"'))
        assert.ok(containers.includes('mode="single"'))
        assert.ok(conditions.includes('hideValue={!showRawValue}'))
        assert.ok(conditions.includes('stateColumnAlignment="center"'))
        assert.ok(commonCss.includes('.netdive-detail-evidence-list.has-centered-state-column .netdive-detail-evidence-row__state'))
        assert.ok(commonCss.includes('minmax(72px, var(--netdive-detail-condition-state-width))'))
        assert.ok(!podCss.includes('centered-state-column'))
        assert.ok(volumes.includes('<KubernetesStructuredDataTable'))
        assert.ok(volumes.includes("if (state === 'none') return '마운트 없음'"))
        assert.ok(volumes.includes("if (state === 'notApplicable') return '해당 없음'"))
        assert.ok(volumes.includes("return '수집되지 않음'"))
        assert.ok(volumes.includes('title="참조 대상"'))
        assert.ok(volumes.includes('title="마운트 정보"'))
        assert.ok(volumes.includes('export const KubernetesVolumeDetailModal'))
        assert.ok(volumes.includes('volume.references.length === 1 ? <BasicInfoRows'))
        assert.ok(volumes.includes('volume.mountState === \'mounted\' ? <div'))
        assert.ok(volumes.includes('className="netdive-k8s-modal-structured-rows"'))
        assert.ok(volumes.includes('className="netdive-k8s-volume-detail__container-value"'))
        assert.ok(volumes.includes('className={`netdive-k8s-volume-detail__empty is-${volume.mountState}`}'))
        assert.ok(!volumes.includes('copyText={volume.name}'))
        assert.ok(!volumes.includes('volume.referenceName'))
        assert.ok(pod.includes('rawStatusLabel="파드 상태"'))
        assert.ok(pod.includes('title="파드 상태 조건"'))
        assert.ok(structured.includes("variant === 'subject' ? <React.Fragment>{nameRow}{kind}</React.Fragment>"))
        assert.ok(structured.includes('netdive-k8s-modal-resource-context__supporting-name-row'))
        assert.ok(!containers.includes('`${container.runtime.restartCount}회`} · {container.image}'))
        assert.ok(!podCss.includes('netdive-k8s-pod-detail__container'))
        assert.ok(!podCss.includes('netdive-k8s-pod-detail__resources'))
    })

    it('keeps workload and storage topology nodes on one fixed three-line card contract', () => {
        const topology = read('src/Topology.tsx')
        const topologyCss = read('src/Topology.css')
        const presentation = read('src/KubernetesTopologyNodePresentation.ts')
        assert.ok(topology.includes('const topologyWorkloadCardHeight = 108'))
        assert.ok(topology.includes('const topologyWorkloadTitleLineGap = 18'))
        assert.ok(topology.includes('isKubernetesThreeLineCardNode(d.data.wrapped) ? topologyWorkloadCardHeight : topologyCardHeight'))
        assert.ok(topology.includes('targetLines = [resourceNameLines[0] || resourceText.name, resourceNameLines[1] || "\\u00a0", resourceText.kind]'))
        assert.ok(topology.includes('secondaryLineIndex = 2'))
        assert.ok(topology.includes('secondaryLineClass = "node-card-title-kubernetes-kind"'))
        assert.ok(topology.includes('isKubernetesThreeLineCard'))
        assert.ok(topology.includes('function kubernetesNodeNamespace(nodeData: any): string'))
        assert.ok(!topology.includes('const kubernetesNodeNamespace ='))
        assert.ok(topologyCss.includes('.node-card-title .node-card-title-kubernetes-kind'))
        assert.ok(topologyCss.includes('font-size: 14px'))
        assert.ok(presentation.includes("deployment: 'Deployment'"))
        assert.ok(presentation.includes("statefulset: 'StatefulSet'"))
        assert.ok(presentation.includes("daemonset: 'DaemonSet'"))
        assert.ok(presentation.includes("return `PVC${namespaceName ? ` · ${namespaceName}` : ''}`"))
        assert.ok(presentation.includes("if (normalized === 'persistentvolume') return 'PV'"))
    })

    it('keeps StatefulSet detail on shared long-value, resource and relationship grammar', () => {
        const workload = read('src/DataPanels/KubernetesWorkloadDetailPanel.tsx')
        const workloadCss = read('src/DataPanels/KubernetesWorkloadDetailPanel.css')
        const common = read('src/DataPanels/common/DetailComponents.tsx')
        const commonCss = read('src/DataPanels/common/DetailComponents.css')
        const recentEvents = read('src/DataPanels/common/KubernetesRecentEvents.tsx')
        const selectionStyles = read('src/SelectionPanelStyles.ts')
        assert.ok(workload.includes('<DetailLongValue'))
        assert.ok(workload.includes('<KubernetesContainerDetails'))
        assert.ok(read('src/DataPanels/common/KubernetesContainerDetails.tsx').includes('<KubernetesResourceConfigurationRows'))
        assert.ok(workload.includes('<KubernetesSelectorSummary selector={selector}'))
        assert.ok(workload.includes('{ label: KUBERNETES_DETAIL_LABELS.selector'))
        assert.ok(!workload.includes("{ label: 'Selector'"))
        assert.ok(workload.includes('<KubernetesReplicaSummary'))
        assert.ok(workload.includes("const operationalMetrics = kind === 'statefulset' || kind === 'deployment' || kind === 'daemonset' ? []"))
        assert.ok(!workload.includes('<DetailMetricSummaryRow'))
        assert.ok(workload.includes('kubernetesCreationTimestamp(data)'))
        assert.ok(workload.includes('collectClaims(spec?.Template?.Spec'))
        assert.ok(workload.includes('lookbackLabel="최근 1시간"'))
        assert.ok(workload.includes("label: '누적 Evicted 파드'"))
        assert.ok(workload.includes("normalizeList(status.Conditions).length > 0"))
        assert.ok(workload.includes("title: '파드'"))
        assert.ok(workload.includes("title: '서비스'"))
        assert.ok(workload.includes("title: 'PVC'"))
        assert.ok(workload.includes('spec.ServiceName'))
        assert.ok(workload.includes('EndpointSlice') || workload.includes("['endpointslice']"))
        assert.ok(workload.includes('PersistentVolumeClaim'))
        assert.ok(!workload.includes('StatefulSet의 현재 Replica/Rollout 집계입니다.'))
        assert.ok(!workloadCss.includes('container-resources'))
        assert.ok(!workloadCss.includes('netdive-k8s-workload-detail__selector'))
        assert.ok(common.includes('export const DetailMetricSummaryRow'))
        const replicaSummary = read('src/DataPanels/common/KubernetesReplicaSummary.tsx')
        assert.ok(replicaSummary.includes("['desired', 'ready', 'current', 'updated', 'unavailable']"))
        assert.ok(replicaSummary.includes('kubernetesReplicaLabel(term, true)'))
        assert.ok(commonCss.includes('.netdive-detail-metric-summary-row'))
        assert.ok(commonCss.includes('.netdive-connected-resource-list__item-layout > .netdive-connected-resource-list__item-icon'))
        assert.ok(commonCss.includes('.netdive-connected-resource-list__item-layout > .netdive-connected-resource-list__item-icon > *'))
        assert.ok(commonCss.includes('max-height: var(--netdive-detail-line-primary-value-two-lines)'))
        assert.ok(recentEvents.includes('lookbackLabel ? `${lookbackLabel} 동안 발생한 중요 이벤트가 없습니다.`'))
        assert.ok(selectionStyles.includes("flex: '0 0 30px'"))
    })

    it('keeps Deployment rollout, conditions and relations on shared contracts', () => {
        const workload = read('src/DataPanels/KubernetesWorkloadDetailPanel.tsx')
        const replicaSummary = read('src/DataPanels/common/KubernetesReplicaSummary.tsx')
        const conditions = read('src/DataPanels/common/KubernetesConditionRows.tsx')
        const common = read('src/DataPanels/common/DetailComponents.tsx')
        const commonCss = read('src/DataPanels/common/DetailComponents.css')
        const app = read('src/App.tsx')
        assert.ok(workload.includes("terms={['desired', 'available', 'updated', 'unavailable']}"))
        assert.ok(workload.includes("kind === 'statefulset' || kind === 'deployment' || kind === 'daemonset' ? []"))
        assert.ok(workload.includes("label: '최대 추가 배포'"))
        assert.ok(workload.includes("label: '최대 미가용'"))
        assert.ok(workload.includes('<KubernetesConditionRows'))
        assert.ok(workload.includes('DEPLOYMENT_CONDITION_DEFINITIONS'))
        assert.ok(workload.includes("title: 'ReplicaSet'"))
        assert.ok(workload.includes('kubernetesReplicaSetRelationsForDeployment'))
        assert.ok(workload.includes('const pods = this.pods()'))
        assert.ok(replicaSummary.includes('props.terms || defaultTerms'))
        assert.ok(common.includes('repeat(${columnCount}'))
        assert.ok(!commonCss.includes('grid-template-columns: repeat(5'))
        assert.ok(conditions.includes('<StatusEvidenceRow'))
        assert.ok(commonCss.includes('.netdive-connected-resource-list__item.ant-btn,'))
        assert.ok(common.includes('className="netdive-connected-resource-list__item-layout"'))
        assert.ok(commonCss.includes('-webkit-line-clamp: 2'))
        assert.ok(commonCss.includes('overflow-wrap: anywhere'))
        assert.ok(app.includes('KUBERNETES_INTERMEDIATE_RELATION_TYPES = new Set(["replicaset"])'))
        assert.ok(app.includes('KUBERNETES_INTERMEDIATE_RELATION_TYPES.has(type)) return false'))
        assert.ok(app.includes('pod.data.TopologyWorkloadControllerID = workload?.id || ""'))
        assert.ok(!app.includes('KUBERNETES_WORKLOAD_TYPES = new Set<string>(["deployment", "statefulset", "daemonset", "job", "cronjob", "replicaset"]'))
        assert.ok(!workload.includes('Deployment의 현재 Replica/Rollout 집계입니다.'))
    })

    it('keeps DaemonSet placement, scheduling and relations on shared contracts', () => {
        const workload = read('src/DataPanels/KubernetesWorkloadDetailPanel.tsx')
        const placement = read('src/DataPanels/common/KubernetesDaemonSetPlacementSummary.tsx')
        const scheduling = read('src/DataPanels/common/KubernetesSchedulingPresentation.ts')
        const presentation = read('src/DataPanels/common/KubernetesDataPresentation.ts')
        const common = read('src/DataPanels/common/DetailComponents.tsx')
        const config = read('src/Config.ts')
        assert.ok(workload.includes('KUBERNETES_DAEMONSET_PLACEMENT_ROLLOUT_TITLE'))
        assert.ok(workload.includes('<KubernetesDaemonSetPlacementSummary {...daemonPlacement} />'))
        assert.ok(workload.includes("kind === 'deployment' || kind === 'statefulset' || kind === 'daemonset'"))
        assert.ok(workload.includes("kind === 'daemonset' ? DAEMONSET_CONDITION_DEFINITIONS"))
        assert.ok(workload.includes("kind === 'daemonset' ? ["))
        assert.ok(workload.includes("{ key: 'pods', title: '파드'"))
        assert.ok(workload.includes("{ key: 'services', title: '서비스'"))
        assert.ok(workload.includes('normalizeKubernetesSchedulingConfiguration'))
        assert.ok(workload.includes("conclusion: '노드 배치 확인 필요'"))
        assert.ok(!workload.includes('노드 배치 상태 확인 필요'))
        assert.ok(config.includes('"kubernetesHeroWorkerFailure": "노드 {count}대 장애"'))
        assert.ok(!config.includes('"kubernetesHeroWorkerFailure": "Worker Node {count}대 장애"'))
        assert.ok(workload.includes('<KubernetesSchedulingModalAction'))
        assert.ok(workload.includes("...((kind === 'deployment' || kind === 'daemonset')"))
        assert.ok(!workload.includes('DaemonSet의 현재 Replica/Rollout 집계입니다.'))
        assert.ok(placement.includes("const placementTerms: KubernetesDaemonSetNodeTerm[] = ['desired', 'current', 'ready', 'available', 'updated']"))
        assert.ok(placement.includes("const anomalyTerms: KubernetesDaemonSetNodeTerm[] = ['unavailable', 'misscheduled']"))
        assert.ok(placement.includes('<DetailCardSubsectionHeader title="배치 현황" first'))
        assert.ok(placement.includes('<DetailCardSubsectionHeader title="이상 현황"'))
        assert.ok(placement.includes('<DetailMetricSummaryRow variant="supporting"'))
        assert.ok(workload.includes("<DetailCardSubsectionHeader title={translate('kubernetesWorkloadConfiguration')}"))
        assert.ok(workload.includes('hierarchy="supporting"'))
        assert.ok(scheduling.includes('nodeSelectionCount'))
        assert.ok(scheduling.includes('tolerationCount'))
        assert.ok(presentation.includes("desired: '배치 대상 노드'"))
        assert.ok(presentation.includes("misscheduled: '비대상 배치'"))
        assert.ok(common.includes('items.length > columnCount'))
    })

    it('keeps all shared Kubernetes detail typography on the 11px semantic floor', () => {
        const tokens = read('src/DataPanels/common/DetailDesignTokens.css')
        ;[
            '--netdive-detail-font-evidence-value: 12px',
            '--netdive-detail-font-evidence-score: 13px',
            '--netdive-detail-line-evidence-value: 18px',
            '--netdive-detail-weight-evidence-number: 600',
            '--netdive-detail-weight-evidence-grade: 500',
            '--netdive-detail-weight-evidence-score: 600'
        ].forEach(token => assert.ok(tokens.includes(token), `missing shared evidence token: ${token}`))
        const files = [
            'src/DataPanels/common/DetailComponents.css',
            'src/DataPanels/common/KubernetesAnalysisConfidence.css',
            'src/DataPanels/common/KubernetesPodUsageTable.css',
            'src/DataPanels/common/KubernetesRecentEvents.css',
            'src/DataPanels/common/KubernetesStatusPolicy.css',
            'src/DataPanels/common/NodeContextBreadcrumb.css',
            'src/DataPanels/KubernetesClusterDetailPanel.css',
            'src/DataPanels/KubernetesNamespaceDetailPanel.css',
            'src/DataPanels/KubernetesNodeDetailPanel.css',
            'src/DataPanels/KubernetesWorkloadDetailPanel.css',
            'src/DataPanels/KubernetesPodDetailPanel.css',
            'src/DataPanels/KubernetesServiceDetailPanel.css',
            'src/DataPanels/KubernetesStorageDetailPanel.css',
            'src/DataPanels/KubernetesRelationshipResourceDetailPanel.css'
        ]
        const belowMinimum = /font-size:\s*(?:[0-9](?:\.[0-9]+)?|10(?:\.[0-9]+)?)px/g
        const fractionalExceptions = /font-size:\s*(?:10\.5|11\.5|12\.5)px/g
        files.forEach(file => {
            const css = read(file)
            assert.strictEqual(css.match(belowMinimum), null, `${file} contains a font below 11px`)
            assert.strictEqual(css.match(fractionalExceptions), null, `${file} contains an ad-hoc fractional font size`)
        })
    })
})
