import * as assert from 'assert'
import * as fs from 'fs'
import * as path from 'path'

const root = path.resolve(__dirname, '..')
const read = (file: string) => fs.readFileSync(path.join(root, file), 'utf8')

describe('Topology context menu contract', () => {
    it('allows the Kubernetes product layer to be active before resources arrive', () => {
        const topology = read('src/Topology.tsx')
        const topologyCss = read('src/Topology.css')
        const app = read('src/App.tsx')
        const activeTagStart = topology.indexOf('    activeNodeTag(tag: string)')
        const activeTagEnd = topology.indexOf('\n    refreshDisplayFilters()', activeTagStart)
        const activeTagImplementation = topology.slice(activeTagStart, activeTagEnd)

        assert.ok(activeTagImplementation.includes("this.nodeTagStates.has(tag) || tag.toLowerCase() === 'kubernetes'"))
        assert.ok(activeTagImplementation.includes('this.nodeTagStates.set(tag, true)'))
        assert.ok(activeTagImplementation.includes('this.nodeTagActive = tag'))
        assert.ok(app.includes('tag: "kubernetes"'))
        assert.ok(topology.includes("const emptyKubernetesLayer = this.nodeTagActive.toLowerCase() === 'kubernetes'"))
        assert.ok(topology.includes('표시할 Kubernetes 리소스가 없습니다.'))
        assert.ok(topology.includes('클러스터가 연결되거나 수집되면 이 화면에 자동으로 표시됩니다.'))
        assert.ok(topologyCss.includes('.topology-empty-layer'))
    })

    it('uses the shared navigation menu and removes capture actions', () => {
        const topology = read('src/Topology.tsx')
        const config = read('src/Config.ts')
        const defaultMenu = config.slice(
            config.lastIndexOf('    nodeMenu(node: Node): Array<MenuItem> {'),
            config.lastIndexOf('    nodeTags(data: any): Array<string> {')
        )

        ;[
            "text: '상세 보기'",
            "text: '화면 중앙으로 이동'",
            "text: connectionFocusActive ? '연결 관계 강조 해제' : '연결 자원 강조'",
            "text: isExpanded ? '하위 자원 접기' : '하위 자원 펼치기'",
            "text: problemFocusActive ? '이상 경로 보기 해제' : '이상 경로 보기'",
            "text: '이름 복사'"
        ].forEach(label => assert.ok(topology.includes(label), `missing menu item: ${label}`))
        assert.ok(topology.includes("type TopologyFocusMode = 'connections' | 'problems'"))
        assert.ok(topology.includes('kubernetesTopologyAttentionPathIDs'))
        assert.ok(topology.includes("classed('topology-focus-dim'"))
        assert.ok(defaultMenu.includes('캡처 작업은 상세 패널에서만 제공합니다.'))
        assert.ok(!defaultMenu.includes('new window.API.CapturesApi'))
    })

    it('keeps context actions capability-based and restores focus', () => {
        const topology = read('src/Topology.tsx')
        const connectionFocus = read('src/TopologyConnectionFocus.ts')
        const menu = read('src/TopologyContextMenu.tsx')
        const topologyCss = read('src/Topology.css')
        const focusStart = topology.indexOf('    private connectionFocus(')
        const focusEnd = topology.indexOf('\n    /**', focusStart)
        const focusImplementation = topology.slice(focusStart, focusEnd)
        const publicFocusStart = topology.indexOf('    focusNodeConnections(')
        const publicFocusEnd = topology.indexOf('\n    private topologyFocusTargetExists', publicFocusStart)
        const publicFocusImplementation = topology.slice(publicFocusStart, publicFocusEnd)
        const toggleFocusStart = topology.indexOf('    private toggleTopologyNodeFocus(')
        const toggleFocusEnd = topology.indexOf('\n    private applyTopologyNodeFocus', toggleFocusStart)
        const toggleFocusImplementation = topology.slice(toggleFocusStart, toggleFocusEnd)
        const problemTargetStart = topology.indexOf('    private isKubernetesProblemPathTarget(')
        const problemResourceStart = topology.indexOf('    private problemPathResourceIDs(', problemTargetStart)
        const problemTargetImplementation = topology.slice(problemTargetStart, problemResourceStart)
        const problemResourceEnd = topology.indexOf('\n    private problemPathFocus(', problemResourceStart)
        const problemResourceImplementation = topology.slice(problemResourceStart, problemResourceEnd)
        const problemFocusStart = topology.indexOf('    private problemPathFocus(')
        const problemFocusEnd = topology.indexOf('\n    private connectionFocus(', problemFocusStart)
        const problemFocusImplementation = topology.slice(problemFocusStart, problemFocusEnd)
        assert.ok(topology.includes('if (connectionFocus.nodeIDs.size > 1)'))
        assert.ok(topology.includes('if (hasChildren)'))
        assert.ok(topology.includes('if (hasProblemPath)'))
        assert.ok(topology.includes('this.clearTopologyNodeFocus()'))
        assert.ok(topology.includes('this.applyTopologyNodeFocus()'))
        assert.ok(topology.includes('Direct neighbors are not'))
        assert.ok(topology.includes('explicitTargetNodeIDs'))
        assert.ok(!topology.includes('includeFirstVisibleChildren(child)'))
        assert.ok(connectionFocus.includes('Traversal is monotonic toward the top of the topology'))
        assert.ok(connectionFocus.includes('appendUpstream'))
        assert.ok(connectionFocus.includes('if (levelDelta === 0) return'))
        assert.ok(focusImplementation.includes("this.gLinks.selectAll('path.link').each"))
        assert.ok(focusImplementation.includes('if (!link || this.linkDisplayOpacity(link) <= 0) return'))
        assert.ok(focusImplementation.includes('Only these edges may receive the visual highlight treatment'))
        assert.ok(focusImplementation.includes("this.gHieraLinks.selectAll('path.hiera-link').each"))
        assert.ok(focusImplementation.includes("const hierarchyPathPrefix = 'hierarchy:'"))
        assert.ok(focusImplementation.includes('this.links.forEach((link: Link)'))
        assert.ok(focusImplementation.includes('visibleRelationLinkIDs.has(linkID)'))
        assert.ok(focusImplementation.includes('!linkID.startsWith(hierarchyPathPrefix)'))
        assert.ok(!topology.includes('isConnectionFocusRelationLink'))
        assert.ok(publicFocusImplementation.includes('this.selectNode(nodeID, true)'))
        assert.ok(toggleFocusImplementation.includes("if (mode === 'connections')"))
        assert.ok(toggleFocusImplementation.includes('this.selectNode(d.data.id, true)'))
        assert.ok(toggleFocusImplementation.indexOf('this.selectNode(d.data.id, true)')
            < toggleFocusImplementation.indexOf('this.connectionFocus(rendered)'))
        assert.ok(problemResourceImplementation.includes('kubernetesTopologyAttentionPathIDs'))
        assert.ok(problemTargetImplementation.includes("this.nodeTagActive.toLowerCase() !== 'kubernetes'"))
        assert.ok(problemTargetImplementation.includes('if (isKubernetesTopologyData(node.data)) return true'))
        assert.ok(problemTargetImplementation.includes('node.data?.IsTopologyGroup'))
        assert.ok(problemTargetImplementation.includes('some(child => isKubernetesTopologyData(child.data))'))
        assert.ok(problemResourceImplementation.includes('if (!this.isKubernetesProblemPathTarget(node)) return new Set<string>()'))
        assert.ok(problemFocusImplementation.includes('hierarchyLinkKeys.add'))
        assert.ok(problemFocusImplementation.includes('relationLinkIDs: new Set<string>()'))
        assert.ok(problemFocusImplementation.includes('private expandProblemPathResources'))
        assert.ok(problemFocusImplementation.includes('node.children || []'))
        assert.ok(problemFocusImplementation.includes('this.nodeGroup.get(id)'))
        assert.ok(problemFocusImplementation.includes('state.groupFullSize = true'))
        assert.ok(problemFocusImplementation.includes('private toggleProblemPathFocus'))
        assert.ok(problemFocusImplementation.includes('if (!this.isKubernetesProblemPathTarget(d.data.wrapped)) return'))
        assert.ok(problemFocusImplementation.includes("this.toggleTopologyNodeFocus(\n            'problems'"))
        assert.ok(topology.includes('const hasProblemPath = this.isKubernetesProblemPathTarget(node)'))
        assert.ok(topology.includes('&& this.problemPathResourceIDs(node).size > 0'))
        assert.ok(topology.includes('callback: () => this.toggleProblemPathFocus(d)'))
        assert.ok(topology.includes("} else if (focus.mode === 'problems')"))
        assert.ok(topology.includes('focus.relationLinkIDs.has(link.id)'))
        assert.ok(topology.includes('focus.visibleRelationLinkIDs.has(link.id)'))
        assert.ok(topology.includes('focus.hierarchyLinkKeys.has(key)'))
        assert.ok(topology.includes('if (event.keyCode === 27)'))
        assert.ok(!topology.includes('this.topologyNodeFocus.focusedNodeID !== id'))
        assert.ok(!topology.includes('this.topologyNodeFocus.focusedNodeID !== d.data.id'))
        assert.ok(topology.includes('topology-connection-focus-status'))
        assert.ok(topology.includes('연결 관계 강조'))
        assert.ok(topology.includes('topology-connection-focus-status__keycap'))
        assert.ok(topology.includes('topology-connection-focus-status__release'))
        assert.ok(!topology.includes('topology-connection-focus-status__close'))
        assert.ok(topology.includes('NodeIndexOutlined'))
        assert.ok(menu.includes('connections: <NodeIndexOutlined />'))
        assert.ok(topology.includes('연결 관계 강조 해제'))
        assert.ok(topology.includes('private refreshTopologyNodeFocus()'))
        assert.ok(topology.includes('this.renderLinks()\n        this.refreshTopologyNodeFocus()\n        this.applyTopologyNodeFocus()'))
        assert.ok(topology.includes('this.topologyFocusTargetExists(focus.focusedNodeID)'))
        assert.ok(topology.includes('if (this.topologySyncInProgress) return'))
        assert.ok(topology.includes('this.connectionFocus(rendered, relatedNodeIDs)'))
        assert.ok(topology.includes('this.connectionFocus(rendered, focus.relatedNodeIDs)'))
        assert.ok(topology.includes('relatedNodeIDs: Array.from(new Set(relatedNodeIDs))'))
        assert.ok(topology.includes('this.zoomFitFocusedNodes(nodeIDs)'))
        assert.ok(topology.includes('this.renderedNodeBounds(nodeIDs)'))
        assert.ok(!topology.includes("select(`#link-${link.id}`).attr('d')"))
        assert.ok(topology.includes('completeTopologySync()'))
        const app = read('src/App.tsx')
        assert.ok(app.includes('this.tc.resetTree(true)'))
        assert.ok(app.includes('this.tc.completeTopologySync()'))
        assert.ok(!topology.includes('window.setTimeout(() => this.clearTopologyNodeFocus'))
        const nodeTransitionStart = topology.indexOf('        node.transition()')
        const nodeTransitionEnd = topology.indexOf('        node\n            .filter', nodeTransitionStart)
        const nodeTransition = topology.slice(nodeTransitionStart, nodeTransitionEnd)
        assert.ok(!nodeTransition.includes('.attr("class", nodeClass)'))
        assert.ok(topologyCss.includes('filter: opacity(16%)'))
        assert.ok(topologyCss.includes('.links .link.topology-focus-hit'))
        assert.ok(!topologyCss.includes('.hiera-link.topology-focus-hit'))
        const focusHitCss = topologyCss.slice(topologyCss.indexOf('.links .link.topology-focus-hit'), topologyCss.indexOf('.topology-connection-focus-status'))
        assert.ok(!focusHitCss.includes('opacity: 1 !important'))
        assert.ok(menu.includes("renderSection('navigation', '탐색')"))
        assert.ok(menu.includes("renderSection('topology', '토폴로지')"))
        assert.ok(menu.includes('<Menu.Item key={action.key} icon={actionIcon(action.key)}>'))
    })

    it('shares the rendered direct-level Badge children with group detail rows', () => {
        const topology = read('src/Topology.tsx')
        const app = read('src/App.tsx')
        const selection = read('src/SelectionPanel.tsx')
        const groupDetail = read('src/DataPanels/GroupDetailPanel.tsx')

        assert.ok(topology.includes('topologyBadgeChildren(node: Node): Node[]'))
        assert.ok(topology.includes('return this.renderedKubernetesBadgeChildren(rendered.data)'))
        assert.ok(topology.includes('this.synthesizedKubernetesBadgeChildren(node)'))
        assert.ok(topology.includes('Pods are the actual next layer below a workload'))
        assert.ok(topology.includes('normalizeTreeHeight inserts Hidden wrappers'))
        assert.ok(topology.includes('collectNextRendered(child.children)'))
        assert.ok(app.includes('this.tc.topologyBadgeChildren(node)'))
        assert.ok(selection.includes('topologyBadgeChildren={this.props.topologyBadgeChildren}'))
        assert.ok(groupDetail.includes('kubernetesTopologyCountBadges(node, badgeChildren)'))
        assert.ok(groupDetail.includes('kubernetesTopologyBadgeGroupSummary(node, topologyBadges, badgeChildren)'))
    })

    it('keeps Kubernetes level gaps independent from resource type', () => {
        const topology = read('src/Topology.tsx')
        assert.ok(topology.includes('? nodeHeight + (topologyWorkloadCardHeight - topologyCardHeight)'))
        assert.ok(!topology.includes('kubernetesWorkloadVerticalGapBoost'))
    })

    it('keeps display-only Down filtering separate from canonical Badge aggregation', () => {
        const app = read('src/App.tsx')
        const topology = read('src/Topology.tsx')
        assert.ok(app.includes('표시 옵션'))
        assert.ok(app.includes('다운된 노드 숨기기'))
        assert.ok(app.includes('if (this.isKubernetesLayerActive()) return null'))
        assert.ok(app.includes('if (this.isKubernetesLayerActive()) return true'))
        assert.ok(app.includes("setTopologyDisplayOption('hideDownNodes'"))
        assert.ok(app.includes('displayNodeVisible={this.topologyDisplayNodeVisible.bind(this)}'))
        assert.ok(topology.includes('displayNodeVisible?: (node: Node) => boolean'))
        assert.ok(topology.includes('const filteredDisplayBranch'))
        assert.ok(topology.includes('return [null, []]'))
        assert.ok(topology.includes('this.displayBranchVisible(link.source)'))
        assert.ok(topology.includes('canonicalGroupMembers'))
        assert.ok(topology.includes('Display-only filtering must not alter group identity'))
    })
})
